<?xml version="1.0" ?>
<SmellBaseline>
  <ManuallySuppressedIssues></ManuallySuppressedIssues>
  <CurrentIssues>
    <ID>TooManyFunctions:RecipeDetailsScreen.kt$com.jakubaniola.recipedetails.RecipeDetailsScreen.kt</ID>
  </CurrentIssues>
</SmellBaseline>
